apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: auth
  type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth
# spec:
#   selector:
#     app: auth
#   type: NodePort
#   ports:
#   - name: port1
#     port: 80
#     targetPort: 80
#     nodePort: 31080
#     protocol: TCP