apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
      - name: report
        image: duynguyen21vnlp/ms-report:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: PORT
            value: '80'
          - name: AUTH_SERVICE
            value: http://auth
          - name: TASK_SERVICE
            value: http://task
          - name: MEMBER_SERVICE
            value: http://member
          - name: NOTIFICATION
            value: http://notification
          - name: REPORT
            value: http://report
      imagePullSecrets:
      - name: regcred
        # ports:
        # - containerPort: 80